- service/grails-app/conf/application-vagrant-db.yml
- service/src/main/okapi/DeploymentDescriptorDev-template.json
Adjsted ports within vagrant-db yaml and descriptor dev template from '8077' to '8076', this is most likely due to missed changes on initial setups
> fix: Port adjustment

- service/grails-app/domain/org/olf/internalPiece/InternalPiece.groovy
- service/grails-app/domain/org/olf/templateConfig/templateMetadataRuleFormat/EnumerationCyclicalTMRF.groovy
- service/grails-app/migrations/create-mod-serials-management.groovy
- service/grails-app/services/org/olf/PieceGenerationService.groovy
- service/grails-app/services/org/olf/PieceLabellingService.groovy
- service/src/main/groovy/org/olf/templating/LabelTemplateBindings.groovy
Added conditionals to standardTM date field if handling a combination piece
Fixed handling of combination/omitted pieces within piecelabellingservice
Added optional chaining to the template metadata rules if no templating rules are passed through
Fixed calculations for enumeration cyclical values
> fix: Templating Omission/Combinations

- service/src/main/groovy/org/olf/templating/LabelTemplateBindings.groovy
Updated enumeration template bindings to use preffered format of {{enumeration1}} for EnumerationTextual as opposed to {{enumeration1.value}}, and  {{enumeration1.level1}} for EnumerationNumeric instead of {{enumeration.levels.0.value}}
> feat: Enumeration template bindings format

- service/grails-app/controllers/org/olf/PredictedPieceSetController.groovy
- service/grails-app/domain/org/olf/PredictedPieceSet.groovy
- service/grails-app/domain/org/olf/templateConfig/templateMetadataRuleFormat/EnumerationNumericLevelTMRF.groovy
- service/grails-app/domain/org/olf/templateConfig/templateMetadataRuleFormat/EnumerationNumericTMRF.groovy
- service/grails-app/domain/org/olf/templateConfig/templateMetadataRuleFormat/EnumerationTextualTMRF.groovy
- service/grails-app/migrations/create-mod-serials-management.groovy
Fixed an issue in which TMRFLevels were not being saved or accessed when attempted to generate and save predicted pieces
> fix: Saving TMRFLevel

- service/grails-app/controllers/org/olf/PredictedPieceSetController.groovy
Refactored generation and saving of predicted pieces so now only the ruleset id is required and serial is fetched from owner
> refactor: Generate predicted pieces parameters

- service/grails-app/domain/org/olf/templateConfig/TemplateConfig.groovy
Changed template configs rules contraint to be nullable, as a template string is required but rules are not
> fix: Template config rules nullable

- service/grails-app/domain/org/olf/PredictedPieceSet.groovy
- service/grails-app/domain/org/olf/Serial.groovy
- service/grails-app/domain/org/olf/templateConfig/TemplateConfig.groovy
- service/grails-app/domain/org/olf/templateConfig/templateMetadataRule/TemplateMetadataRule.groovy
- service/grails-app/domain/org/olf/templateConfig/templateMetadataRule/TemplateMetadataRuleType.groovy
- service/grails-app/domain/org/olf/templateConfig/templateMetadataRuleFormat/EnumerationNumericLevelTMRF.groovy
- service/grails-app/domain/org/olf/templateConfig/templateMetadataRuleFormat/EnumerationNumericTMRF.groovy
- service/grails-app/domain/org/olf/templateConfig/templateMetadataRuleFormat/EnumerationTextualLevelTMRF.groovy
- service/grails-app/domain/org/olf/templateConfig/templateMetadataRuleFormat/EnumerationTextualTMRF.groovy
- service/grails-app/migrations/create-mod-serials-management.groovy
Added index properties to template metadata rules and enumeration levels to ensure order is maintained when predicted pieces are generated from database
> feat: Template config ordering

- service/grails-app/controllers/org/olf/PredictedPieceSetController.groovy
- service/grails-app/domain/org/olf/templateConfig/templateMetadataRuleFormat/EnumerationNumericLevelTMRF.groovy
Updated how starting values are binded within predicted piece set generation to ensure results are correctly saved
> fix: Starting value binding fix

- service/src/main/okapi/ModuleDescriptor-template.json
Added optional dependency on mod-orders to the mod-serials-management module descriptor
[MODSER-12](https://folio-org.atlassian.net/browse/MODSER-12)
> build: Added orders optional dependency

- openapi/serials-management.yaml
Adds endpoints:
- /serials-management/refdata/{uuid} GET
- /serials-management/refdata POST
- /serials-management/refdata/{uuid} PUT
- /serials-management/refdata/{uuid} DELETE
- /serials-management/refdata/{domain}/{property} GET
- /serials-management/serials/{uuid} DELETE
- /serials-management/rulesets GET
- /serials-management/rulesets/{uuid} GET
- /serials-management/rulesets/{uuid} DELETE
Corrects some response errors and describes 404 responses more fully
> UISER-20: Extend API documentation

- service/grails-app/domain/org/olf/PredictedPieceSet.groovy
- service/grails-app/views/predictedPieceSet/_predictedPieceSet.gson
Added a transient title field to the predicted piece set model, so that upon viewing the tile will be grabbed from the owner serial
> feat: Transient title value

- service/grails-app/controllers/org/olf/PredictedPieceSetController.groovy
- service/grails-app/domain/org/olf/templateConfig/templateMetadataRule/EnumerationTemplateMetadataRule.groovy
- service/grails-app/domain/org/olf/templateConfig/templateMetadataRuleFormat/EnumerationNumericTMRF.groovy
- service/grails-app/domain/org/olf/templateConfig/templateMetadataRuleFormat/EnumerationTextualTMRF.groovy
- service/grails-app/services/org/olf/PieceGenerationService.groovy
- service/grails-app/services/org/olf/PieceLabellingService.groovy
This PR covers multiple tickets:
- Template does not always get data from labels or levels in the same order
- Level 1 number not used correctly in predicted piece preview from Create Publication Pattern
The starting values have now been parsed out into their own array as opposed to the original usage of transient values within the domain models
[UISER-99](https://folio-org.atlassian.net/browse/UISER-99), [UISER-88](https://folio-org.atlassian.net/browse/UISER-88)
> UISER-99/88: Starting values ordering and missing uses

- service/grails-app/controllers/org/olf/LocalesController.groovy
- service/grails-app/controllers/org/olf/UrlMappings.groovy
- service/grails-app/domain/org/olf/templateConfig/templateMetadataRule/ChronologyTemplateMetadataRule.groovy
- service/grails-app/domain/org/olf/templateConfig/templateMetadataRuleFormat/ChronologyDateTMRF.groovy
- service/grails-app/domain/org/olf/templateConfig/templateMetadataRuleFormat/ChronologyMonthTMRF.groovy
- service/grails-app/domain/org/olf/templateConfig/templateMetadataRuleFormat/ChronologyYearTMRF.groovy
- service/grails-app/migrations/module-tenant-changelog.groovy
- service/grails-app/migrations/update-mod-serials-management-1-1.groovy
- service/src/main/okapi/ModuleDescriptor-template.json
Added ruleLocale field to handle using a 2 letter locale value when generating chronologies
UISER-113
> fix: Support using different languages for chronologies when generating predicted pieces

- service/grails-app/domain/org/olf/internalPiece/templateMetadata/ChronologyUCTMT.groovy
Field was previously called "constraint" caused to saving errors
[MODSER-37](https://folio-org.atlassian.net/browse/MODSER-37)
> fix: Fixed ChronologyUCTMT constraints field

- service/build.gradle
- service/grails-app/domain/org/olf/internalPiece/templateMetadata/EnumerationLevelUCTMT.groovy
- service/grails-app/domain/org/olf/templateConfig/templateMetadataRuleFormat/EnumerationNumericLevelTMRF.groovy
- service/grails-app/domain/org/olf/templateConfig/templateMetadataRuleFormat/EnumerationNumericTMRF.groovy
- service/grails-app/migrations/update-mod-serials-management-1-1.groovy
- service/grails-app/services/org/olf/HousekeepingService.groovy
- service/grails-app/views/enumerationLevelUCTMT/_enumerationLevelUCTMT.gson
Upon adding in the functionality to auto-populate fields based on previously generated predicted piece sets ([UISER-91](https://folio-org.atlassian.net/browse/UISER-91)), we found that it was being populated with the template string value as opposed to the number value it was actually meant to represent, to resolve this we've expanded the EnumerationLevelUCTMT domain model to include the raw value and value format
> fix: EnumerationLevelUCTMT value handling

- service/grails-app/conf/logback-development.xml
- service/grails-app/conf/logback.xml
Added hibernate deprecation logging to logback filies to fix excessive logging of "Hibernate's legacy org.hibernate.Criteria API is deprecated" warning
> chore: Hibernate deprecation logging

- service/grails-app/views/omissionRule/_omissionRule.gson
Fixed an issue in which the timeUnit refdata was not expanded within the omission rule view
> fix: Expanded time unit within omission rule

- service/grails-app/controllers/org/olf/PredictedPieceSetController.groovy
- service/grails-app/controllers/org/olf/SerialRulesetController.groovy
- service/grails-app/controllers/org/olf/UrlMappings.groovy
- service/grails-app/domain/org/olf/recurrence/Recurrence.groovy
- service/grails-app/services/org/olf/HousekeepingService.groovy
- service/grails-app/services/org/olf/SerialRulesetService.groovy
- service/src/main/okapi/ModuleDescriptor-template.json
Purpose:
To support an edit option for publication patterns that have not yet been used to generate predicted pieces. If there are any predicted piece sets linked to a publication pattern it will not be possible to edit the pattern (although an active pattern can be deprecated by making a new active pattern as currently)
> UISER-153: Support edit for publication patterns

- service/grails-app/views/internalCombinationPiece/_internalCombinationPiece.gson
- service/grails-app/views/internalOmissionPiece/_internalOmissionPiece.gson
- service/grails-app/views/internalPiece/_internalPiece.gson
- service/grails-app/views/internalRecurrencePiece/_internalRecurrencePiece.gson
Previously, internal recurrence/omission/combination pieces were not expanding the fields contained within their models, in order to fix this, the internal piece view file has been changes to dynamically select the correct internal piece view file based on the class, additionally a class field has been added to allow for easier identification of the piece class on the front end
> MODSER-56: Internal omission/combination pieces not expanding fields

- service/grails-app/controllers/org/olf/PredictedPieceSetController.groovy
- service/grails-app/services/org/olf/PieceGenerationService.groovy
- service/src/integration-test/groovy/org/olf/PredictedPieceSetSpec.groovy
- service/src/integration-test/resources/ruleset_data.json
Presently the generate and create methods within the predicted piece set controller return two separate objects, the former returns an array of InternalPieces whereas the latter returns the entire PredictedPieceSet object, in order to reduce confusion, and to ensure consistency, both these methods should return the entire PredictedPieceSet object, the only difference being that the create endpoint should save and the generate endpoint should not
> MODSER-57: Generate/create piece set endpoints to return same objects

- GUIDANCE.md
- LICENSE
- service/build.gradle
Bumped dependency for web-toolkit to 10.0.1 and grails-okpai to 7.3.0
updated license.md and added guidance.md file
> MODSER-50: Update module license, guidance and dependencies

- NEWS.md
- service/build.gradle
- service/gradle.properties
- service/src/main/okapi/ModuleDescriptor-template.json
Separate out okapiInterfaceVersion from module version so future module major bumps that don't change interface shape can be handled separately
> build: okapiInterfaceVersion

- service/grails-app/views/internalCombinationPiece/_internalCombinationPiece.gson
- service/grails-app/views/internalOmissionPiece/_internalOmissionPiece.gson
- service/grails-app/views/internalPiece/_internalPiece.gson
- service/grails-app/views/internalRecurrencePiece/_internalRecurrencePiece.gson
Fixed a bug in which receiving pieces were not being expanded in the internal piece model
[MODSER-60](https://folio-org.atlassian.net/browse/MODSER-60)
> MODSER-60: Receiving piece count not displaying in predicted piece set

- service/grails-app/controllers/org/olf/PredictedPieceSetController.groovy
- service/grails-app/domain/org/olf/templateConfig/templateMetadataRuleFormat/EnumerationNumericTMRF.groovy
- service/grails-app/services/org/olf/PieceLabellingService.groovy
Fixed an issue in which multiple levels of continuous enumeration caused the starting values to not be used correctly when calculating the enumaration levels, a refactor to how we calculate enumeration numeric levels has been implemented and tests will be put in place to clarify this
> fix: Multiple levels of continuous enumeration in a publication pattern result in incorrect numbering

- service/grails-app/controllers/org/olf/PredictedPieceSetController.groovy
- service/grails-app/domain/org/olf/PredictedPieceSet.groovy
- service/grails-app/migrations/module-tenant-changelog.groovy
- service/grails-app/migrations/update-mod-serials-management-1-2.groovy
- service/grails-app/services/org/olf/PieceGenerationService.groovy
Added use of numberOfCycles to determine how many years the ruleset should be run for within the PieceGenerationService
MODSER-67
> MODSER-67: Support option to generate multiple years/cycles when generating predicted pieces

- service/grails-app/services/org/olf/PieceLabellingService.groovy
Fixed an issue in which continuationPieceRecurrenceMetadata was storing incorrect enumeration values, due to attempts to access a non-existent index
MODSER-71
> MODSER-71: continuationPieceRecurrenceMetadata stores incorrect enumeration rawValues/values

- service/grails-app/services/org/olf/PieceLabellingService.groovy
Due to refactors in a previous issue, generating the label template bindings for combined pieces now cause the next piece to use the incorrect bindings instead of following on from where the combined piece left off
UISER-190
> UISER-190: Combined enumeration does not skip the combined issue numbers

- service/grails-app/controllers/org/olf/PredictedPieceSetController.groovy
- service/grails-app/services/org/olf/PieceLabellingService.groovy
Removed methods within piece labelling service for supporting older shapes of starting values
> refactor: Removed old starting value shape support

- service/grails-app/domain/org/olf/templateConfig/templateMetadataRuleFormat/EnumerationTextualTMRF.groovy
Changed refdata category on EnumerationTextual to nullable false to prevent old ramsons data from causing errors
MODSER-109
> MOSER-109: Refdata category nullable change

- NEWS.md
- service/grails-app/services/org/olf/PieceLabellingService.groovy
With the migration from ramsons to sunflower, an issue has arisen where the indexs of enumeration rules wont line up with starting values, this resolves it by using the internal counter
> MODSER-110: Migrated pattern (Ramsons -> Sunflower) with combination generates incorrect labels for predicted pieces

- service/src/main/okapi/ModuleDescriptor-template.json
[MODORDSTOR-448](https://folio-org.atlassian.net/browse/MODORDSTOR-448) - Make user limit as string field & apply migration
Updated the order-lines interface version
See [acq-models](https://github.com/folio-org/acq-models/pull/519) or [mod-orders-storage](https://github.com/folio-org/mod-orders-storage/pull/476) PRs (there are lots).
> [MODORDSTOR-448] Updated order-lines interface version

- service/grails-app/migrations/add-missing-primary-keys-for-trillium.groovy
Due to migration errors being thrown when attempting to create primary key constraints, this changeset has been reverted for the time being
MODSER-126
> MODSER-126: Removed offending PK constraint
