README.md

Added required copyright/license information to README
In relation to changes requested in [FOLIO-3568](https://issues.folio.org/browse/FOLIO-3568)

docs: Copyright/License

---

service/grails-app/domain/org/olf/Serial.groovy
service/grails-app/migrations/create-mod-serials-management.groovy
service/grails-app/views/serial/_serial.gson
service/src/main/okapi/ModuleDescriptor-template.json

- Added serial status/description to serial domain model
- Added constraints to serial domain model and fixed error in mapping
- Added map for refdata endpoints and associated permissions
[UISER-1](https://issues.folio.org/browse/UISER-1)

feat: Serial description/status

---

service/grails-app/domain/org/olf/Serial.groovy
service/grails-app/domain/org/olf/SerialNote.groovy
service/grails-app/migrations/create-mod-serials-management.groovy
service/grails-app/views/serial/_serial.gson
service/grails-app/views/serialNote/_serialNote.gson

Added serial notes domain model and view file, updated serial domain model and view to include these changes

feat: Serial notes

---

service/grails-app/views/recurrence/_recurrence.gson
service/grails-app/views/recurrencePattern/_recurrencePattern.gson
service/grails-app/views/recurrenceRule/_recurrenceRule.gson

Added view files for recurrence, recurrence rules and recurrence patterns

feat: Recurrence views

---

service/grails-app/domain/org/olf/recurrence/RecurrenceRule.groovy
service/grails-app/domain/org/olf/recurrence/recurrencePattern/RecurrencePattern.groovy
service/grails-app/migrations/create-mod-serials-management.groovy
service/grails-app/views/recurrence/_recurrence.gson
service/grails-app/views/recurrenceRule/_recurrenceRule.gson
service/grails-app/views/serial/_serial.gson

Added version mapping and column to recurrence rule/pattern
Added expand params to serial, recurrence and recurrence rules to ensure all relevant information isincluded in the response

fix: Recurrence version/views

---

service/grails-app/controllers/org/olf/SerialController.groovy
service/grails-app/domain/org/olf/recurrence/RecurrenceRule.groovy
service/grails-app/domain/org/olf/recurrence/recurrencePattern/RecurrencePattern.groovy
service/grails-app/domain/org/olf/recurrence/recurrencePattern/RecurrencePatternMonthWeekday.groovy
service/grails-app/migrations/create-mod-serials-management.groovy
service/grails-app/views/recurrencePattern/_recurrencePatternDay.gson
service/grails-app/views/recurrencePattern/_recurrencePatternMonthDate.gson
service/grails-app/views/recurrencePattern/_recurrencePatternMonthWeekday.gson
service/grails-app/views/recurrencePattern/_recurrencePatternWeek.gson
service/grails-app/views/recurrencePattern/_recurrencePatternYearDate.gson
service/grails-app/views/recurrencePattern/_recurrencePatternYearMonthWeekday.gson
service/grails-app/views/recurrencePattern/_recurrencePatternYearWeekday.gson
service/grails-app/views/recurrenceRule/_recurrenceRule.gson

RecurrenceRule pattern class is now validated based on the patternType supplied by user
Added a parser to serial controller to ensure that the correct recurrence pattern class is used
Added views for all recurrence patterns and dynamic assignment within recurrence rule view for any supported pattern

feat: Recurrence pattern validation

---

service/grails-app/migrations/create-mod-serials-management.groovy

Added foreign key constraints for recurrence pattern ref data values

feat: Recurrence refdata foreign keys

---

service/grails-app/controllers/org/olf/SerialController.groovy

Added conditional to recurrence serial controller to allow for serials to be saved without a recurrence

fix: Recurrence validation conditional

---

service/build.gradle

Bumped dependencies for postgresql, opencsv, kafka-clients, commons-io
[MODSER-1](https://issues.folio.org/browse/MODSER-1)

build: Dependencies

---

service/build.gradle

Bumped hibernate-core dependency to 5.4.33
[MODSER-1](https://issues.folio.org/browse/MODSER-1)

build: Hibernate-core dependency bump

---

service/grails-app/domain/org/olf/recurrence/recurrencePattern/RecurrencePatternYearDate.groovy
service/grails-app/domain/org/olf/recurrence/recurrencePattern/RecurrencePatternYearMonthWeekday.groovy

Updated month labels from "Febuary" to "February"

fix: Month default fix

---

service/grails-app/domain/org/olf/SerialRuleset.groovy
service/grails-app/migrations/create-mod-serials-management.groovy
service/grails-app/views/serialRuleset/_serialRuleset.gson

Added serial ruleset status/description to domain model and migrations

feat: Ruleset status/description

---

service/grails-app/domain/org/olf/recurrence/recurrencePattern/RecurrencePatternMonthWeekday.groovy
service/grails-app/domain/org/olf/recurrence/recurrencePattern/RecurrencePatternWeek.groovy
service/grails-app/domain/org/olf/recurrence/recurrencePattern/RecurrencePatternYearDate.groovy
service/grails-app/domain/org/olf/recurrence/recurrencePattern/RecurrencePatternYearMonthWeekday.groovy
service/grails-app/domain/org/olf/recurrence/recurrencePattern/RecurrencePatternYearWeekday.groovy

Changed Weekday/Month refdata value from RecurrencePattern to Global for use with omissions

refactor: Weekday/Month global refdata

---

service/grails-app/domain/org/olf/SerialRuleset.groovy
service/grails-app/domain/org/olf/combination/Combination.groovy
service/grails-app/domain/org/olf/combination/CombinationRule.groovy
service/grails-app/domain/org/olf/combination/combinationPattern/CombinationPattern.groovy
service/grails-app/domain/org/olf/combination/combinationPattern/CombinationPatternDayInAMonth.groovy
service/grails-app/domain/org/olf/combination/combinationPattern/CombinationPatternMonth.groovy
service/grails-app/domain/org/olf/combination/combinationPattern/CombinationPatternNthIssue.groovy
service/grails-app/domain/org/olf/combination/combinationPattern/CombinationPatternWeek.groovy
service/grails-app/domain/org/olf/combination/combinationPattern/CombinationPatternWeekInAMonth.groovy
service/grails-app/domain/org/olf/combination/combinationPattern/CombinationPatternWeekdayInAWeek.groovy
service/grails-app/domain/org/olf/combination/combinationPattern/CombinationPatternWeekdayInWeekOfAMonth.groovy
service/grails-app/migrations/create-mod-serials-management.groovy
service/grails-app/views/combination/_combination.gson
service/grails-app/views/combinationPattern/_combinationPattern.gson
service/grails-app/views/combinationPattern/_combinationPatternDayInAMonth.gson
service/grails-app/views/combinationPattern/_combinationPatternMonth.gson
service/grails-app/views/combinationPattern/_combinationPatternNthIssue.gson
service/grails-app/views/combinationPattern/_combinationPatternWeek.gson
service/grails-app/views/combinationPattern/_combinationPatternWeekInAMonth.gson
service/grails-app/views/combinationPattern/_combinationPatternWeekdayInAWeek.gson
service/grails-app/views/combinationPattern/_combinationPatternWeekdayInWeekOfAMonth.gson
service/grails-app/views/combinationRule/_combinationRule.gson
service/grails-app/views/serialRuleset/_serialRuleset.gson
service/src/main/groovy/org/olf/combination/CombinationRuleHelpers.groovy
service/src/main/groovy/org/olf/recurrence/RecurrenceRuleHelpers.groovy

Added domain models for combination, combination rule, and the specific combination patterns
Added migrations for new combination domain models
Added views for all combination patterns

feat: Combinations

---

service/grails-app/services/org/olf/PieceGenerationService.groovy

fix: Year ordinal fix

---

service/grails-app/services/org/olf/PieceGenerationService.groovy

Added documentation to piece generation service for future development

docs: PieceGenerationService

---

service/build.gradle
service/grails-app/init/org/olf/Application.groovy

Changed export port from 8078 to 8080
Implemented undertow into the application.groovy

fix: Export port

---

service/grails-app/services/org/olf/PieceGenerationService.groovy

Adjusted currentTimeUnitPeriod to be standardised throughout all time units for consistency
[MODSER-7](https://issues.folio.org/browse/MODSER-7)

fix: Year time unit period

---

service/grails-app/domain/org/olf/omission/omissionPattern/OmissionPatternDay.groovy
service/grails-app/domain/org/olf/omission/omissionPattern/OmissionPatternDayMonth.groovy
service/grails-app/domain/org/olf/omission/omissionPattern/OmissionPatternDayWeek.groovy
service/grails-app/domain/org/olf/omission/omissionPattern/OmissionPatternDayWeekMonth.groovy
service/grails-app/domain/org/olf/omission/omissionPattern/OmissionPatternDayWeekday.groovy
service/grails-app/domain/org/olf/omission/omissionPattern/OmissionPatternIssue.groovy
service/grails-app/domain/org/olf/omission/omissionPattern/OmissionPatternIssueMonth.groovy
service/grails-app/domain/org/olf/omission/omissionPattern/OmissionPatternIssueWeek.groovy
service/grails-app/domain/org/olf/omission/omissionPattern/OmissionPatternIssueWeekMonth.groovy
service/grails-app/domain/org/olf/omission/omissionPattern/OmissionPatternMonth.groovy
service/grails-app/domain/org/olf/omission/omissionPattern/OmissionPatternWeek.groovy
service/grails-app/domain/org/olf/omission/omissionPattern/OmissionPatternWeekMonth.groovy
service/grails-app/services/org/olf/PieceGenerationService.groovy

Added handling of omissions within the piece generation service, along with comparison functions to all omission pattern domain models
[MODSER-5](https://issues.folio.org/browse/MODSER-5)

feat: Omission piece generation

---

service/build.gradle

Bumped kint web toolkit version to 8.0.1-rc.4 from rc.3

build: Web toolkit bump

---

service/grails-app/domain/org/olf/SerialRuleset.groovy
service/grails-app/migrations/create-mod-serials-management.groovy

Added ruleset number field to serial ruleset and updated migrations
[UISER-34](https://issues.folio.org/browse/UISER-34)

feat: Ruleset number

---

service/grails-app/domain/org/olf/SerialRuleset.groovy
service/grails-app/domain/org/olf/label/Label.groovy
service/grails-app/domain/org/olf/label/LabelRule.groovy
service/grails-app/domain/org/olf/label/enumerationLevel/EnumerationLevel.groovy
service/grails-app/domain/org/olf/label/labelFormat/LabelFormat.groovy
service/grails-app/domain/org/olf/label/labelFormat/LabelFormatChronologyDate.groovy
service/grails-app/domain/org/olf/label/labelFormat/LabelFormatChronologyMonth.groovy
service/grails-app/domain/org/olf/label/labelFormat/LabelFormatChronologyYear.groovy
service/grails-app/domain/org/olf/label/labelStyle/LabelStyle.groovy
service/grails-app/domain/org/olf/label/labelStyle/LabelStyleChronology.groovy
service/grails-app/domain/org/olf/label/labelStyle/LabelStyleEnumeration.groovy
service/grails-app/migrations/create-mod-serials-management.groovy
service/grails-app/services/org/olf/PieceGenerationService.groovy
service/grails-app/views/enumerationLevel/_enumerationLevel.gson
service/grails-app/views/label/_label.gson
service/grails-app/views/labelFormat/_labelFormat.gson
service/grails-app/views/labelFormat/_labelFormatChronologyDate.gson
service/grails-app/views/labelFormat/_labelFormatChronologyMonth.gson
service/grails-app/views/labelFormat/_labelFormatChronologyYear.gson
service/grails-app/views/labelRule/_labelRule.gson
service/grails-app/views/labelStyle/_labelStyle.gson
service/grails-app/views/labelStyle/_labelStyleChronology.gson
service/grails-app/views/labelStyle/_labelStyleEnumeration.gson
service/grails-app/views/serialRuleset/_serialRuleset.gson
service/src/main/groovy/org/olf/label/LabelRuleHelpers.groovy
service/src/main/groovy/org/olf/labelStyle/labelStyleHelpers.groovy

Added initial framework for labelling including domain models, migrations and views
[UISER-37](https://issues.folio.org/browse/UISER-37), [UISER-39](https://issues.folio.org/browse/UISER-39)

feat: Labelling framework

---

service/grails-app/domain/org/olf/internalPiece/InternalRecurrencePiece.groovy
service/grails-app/domain/org/olf/internalPiece/internalPieceLabel/InternalPieceChronologyLabel.groovy
service/grails-app/domain/org/olf/internalPiece/internalPieceLabel/InternalPieceLabel.groovy
service/grails-app/domain/org/olf/label/LabelRule.groovy
service/grails-app/domain/org/olf/label/enumerationLevel/EnumerationLevel.groovy
service/grails-app/domain/org/olf/label/labelFormat/LabelFormatChronologyDate.groovy
service/grails-app/domain/org/olf/label/labelFormat/LabelFormatChronologyMonth.groovy
service/grails-app/domain/org/olf/label/labelFormat/LabelFormatChronologyYear.groovy
service/grails-app/domain/org/olf/label/labelStyle/LabelStyleChronology.groovy
service/grails-app/services/org/olf/PieceGenerationService.groovy
service/grails-app/views/internalPieceChronologyLabel/_internalPieceChronologyLabel.gson
service/grails-app/views/internalPieceLabel/_internalPieceLabel.gson
service/grails-app/views/internalRecurrencePiece/_internalRecurrencePiece.gson

Added initial framework for generating chronology labels

feat: Chronology generation

---

service/grails-app/domain/org/olf/internalPiece/internalPieceLabel/EnumerationLabelLevel.groovy
service/grails-app/domain/org/olf/internalPiece/internalPieceLabel/InternalPieceEnumerationLabel.groovy
service/grails-app/domain/org/olf/label/LabelRule.groovy
service/grails-app/domain/org/olf/label/labelStyle/LabelStyleChronology.groovy
service/grails-app/domain/org/olf/label/labelStyle/LabelStyleEnumeration.groovy
service/grails-app/services/org/olf/PieceGenerationService.groovy
service/grails-app/views/enumerationLabelLevel/_enumerationLabelLevel.gson
service/grails-app/views/internalPieceEnumerationLabel/_internalPieceEnumerationLabel.gson

Added enumeration framework and generation

feat: Enumeration framework

---

service/grails-app/domain/org/olf/internalPiece/templateMetadata/EnumerationTemplateMetadata.groovy
service/grails-app/services/org/olf/PieceGenerationService.groovy
service/grails-app/services/org/olf/PieceLabellingService.groovy

Tidied up some completed todos

chore: Todo tidyup

---

service/grails-app/controllers/org/olf/PredictedPieceSetController.groovy

Fixed JSONObject import to be from grails.web instead of org.json to allow for optional chaining

fix: JSONObject import

---

service/grails-app/domain/org/olf/SerialOrderLine.groovy
service/grails-app/migrations/create-mod-serials-management.groovy

Added serial title and titleID property to domain model and database

feat: Serial title property

---

service/grails-app/controllers/org/olf/PredictedPieceSetController.groovy
service/grails-app/domain/org/olf/PredictedPieceSet.groovy
service/grails-app/migrations/create-mod-serials-management.groovy

Removed serial from predicted piece set and replaced with ruleset, serial information can now be rerieved from ruleset owner

feat: PredictedPieceSet ruleset

---

service/grails-app/migrations/create-mod-serials-management.groovy

Fixed saving of internal combination pieces

fix: Combination pieces save

---

service/grails-app/domain/org/olf/internalPiece/InternalPiece.groovy
service/grails-app/migrations/create-mod-serials-management.groovy

Added receivingId property to the internal peice domain model and migrations

feat: Internal piece receiving id

---

service/grails-app/controllers/org/olf/PredictedPieceSetController.groovy

Changed backend code to ensure that the multiply on null error does not occur

fix: Multiply on null fix

---

service/src/integration-test/groovy/org/olf/PredictedPieceSetLifecycleSpec.groovy

Added tests for predicted piece sets endpoint

test: PredictedPieceLifecycle test

---

service/grails-app/controllers/org/olf/PredictedPieceSetController.groovy

Updated array index access to use getAt to ensure no more error when previewing

fix: Piece generation getAt fix

---

service/src/main/okapi/ModuleDescriptor-template.json

Added predicted pieces PUT method to module descriptor handlers

build: Predicted pieces PUT

---

service/grails-app/controllers/org/olf/UrlMappings.groovy
service/src/main/okapi/ModuleDescriptor-template.json

Removed settings endpoint and associated handlers
[MODSER-20](https://folio-org.atlassian.net/browse/MODSER-20)

build: Removed settings endpoint

---

README.md

Adds documentation to readme for running module via vagrant
Adds text to fulfil license compatibility for 3rd party library

UISER-19, UISER-21: Updates to README

---

service/grails-app/controllers/org/olf/SerialRulesetController.groovy
service/grails-app/controllers/org/olf/UrlMappings.groovy
service/grails-app/domain/org/olf/Serial.groovy
service/grails-app/i18n/messages.properties
service/grails-app/services/org/olf/SerialRulesetService.groovy
service/src/main/okapi/ModuleDescriptor-template.json

Upon saving a new ruleset, other active rulesets are now identified and changed to deprecated before saving the newly active ruleset
UISER-35

feat: Add limit to one active publication pattern

---

service/src/main/groovy/org/olf/combination/CombinationRuleHelpers.groovy
service/src/main/groovy/org/olf/omission/OmissionRuleHelpers.groovy
service/src/main/groovy/org/olf/recurrence/RecurrenceRuleHelpers.groovy

Added final to rulepatternvalidator fields
[MODSER-23](https://folio-org.atlassian.net/browse/MODSER-23)

fix: Final public rule pattern validator

---

service/.gitignore
service/build.gradle
service/gradle.properties
service/gradle/wrapper/gradle-wrapper.properties
service/grails-app/conf/application-dc.yml
service/grails-app/conf/application-rancher-desktop-db.yml
service/grails-app/conf/application-vagrant-db.yml
service/grails-app/conf/application.yml
service/src/integration-test/groovy/org/olf/PredictedPieceSetSpec.groovy

Upgrade module to grails 6, including new version of the k-int plugins, and some dependency changes
refs ERM-3111

feat!: Grails 6 upgrade (ERM-3111)

---

service/grails-app/domain/org/olf/internalPiece/InternalPiece.groovy
service/grails-app/domain/org/olf/internalPiece/ReceivingPiece.groovy
service/grails-app/migrations/create-mod-serials-management.groovy
service/grails-app/views/internalPiece/_internalPiece.gson
service/grails-app/views/receivingPiece/_receivingPiece.gson

Handling multiple receiving Ids, as aopposed to a single one

feat: Multiple receiving Ids

---

NEWS.md
service/gradle.properties

chore: Release 1.0.0

---

service/src/main/okapi/ModuleDescriptor-template.json

Added more fine grained control of the permissions within the serials management module descriptor
MODSER-35

MODSER-35: Endpoints should be protected by fine-grained permissions

---

service/src/main/okapi/ModuleDescriptor-template.json

Added missing serial delete permission from module descriptor
MODSER-35

MODSER-35: Added missing serial delete permission

---

NEWS.md
service/gradle.properties

Updated NEWS.md and bumped version to 1.0.2
refs MODSER-36

chore: Release 1.0.2

---

NEWS.md

Added sections to changelog added in 1.0.3 release

docs: Updated changelog after 1.0.3 release

---

service/grails-app/domain/org/olf/templateConfig/templateMetadataRule/ChronologyTemplateMetadataRule.groovy
service/grails-app/domain/org/olf/templateConfig/templateMetadataRule/EnumerationTemplateMetadataRule.groovy
service/grails-app/services/org/olf/HousekeepingService.groovy

Changed default labels for enumneration/chronology format

MODSER-32: Change default labels for chronology/enumeration format

---

service/grails-app/controllers/org/olf/PredictedPieceSetController.groovy
service/grails-app/services/org/olf/PieceLabellingService.groovy

Added support for older shape of starting values on as to prevent issues with older frontend versions

fix: Starting values shapes backporting

---

service/grails-app/domain/org/olf/internalPiece/InternalRecurrencePiece.groovy

Fixed constraints field within Internal reccurence piece so that it functions correctly

fix: InternalRecurrencePiece constraints

---

service/grails-app/controllers/org/olf/PredictedPieceSetController.groovy
service/grails-app/domain/org/olf/PredictedPieceSet.groovy
service/src/main/okapi/ModuleDescriptor-template.json

Added predicted piece set delete endpoint to module descriptor, along with associated permissions

feat: Pieceset delete endpoint

---

service/grails-app/domain/org/olf/SerialRuleset.groovy
service/grails-app/migrations/update-mod-serials-management-1-1.groovy

Added sequence to be used as fallback for serial ruleset numbering and implemented into the rulesets beforeValidate function

MODSER-53: Add fall back for publication pattern numbering

---

NEWS.md
service/gradle.properties
service/grails-app/controllers/org/olf/PredictedPieceSetController.groovy
service/grails-app/domain/org/olf/templateConfig/templateMetadataRuleFormat/EnumerationNumericTMRF.groovy
service/grails-app/services/org/olf/PieceLabellingService.groovy
service/grails-app/views/internalCombinationPiece/_internalCombinationPiece.gson
service/grails-app/views/internalOmissionPiece/_internalOmissionPiece.gson
service/grails-app/views/internalPiece/_internalPiece.gson
service/grails-app/views/internalRecurrencePiece/_internalRecurrencePiece.gson

Added NEWS section and bumped version to 1.1.1
MODSER-65

chore: Release 1.1.1

---

NEWS.md

Added NEWS section reflected in 1.1.1 release

chore: Post-release 1.1.1

---

NEWS.md

Added changelog section reflected in release 1.1.2

chore: Post release 1.1.2

---

service/grails-app/controllers/org/olf/PredictedPieceSetController.groovy
service/grails-app/domain/org/olf/PredictedPieceSet.groovy
service/grails-app/views/predictedPieceSet/_predictedPieceSet.gson
service/src/integration-test/groovy/org/olf/PredictedPieceSetSpec.groovy

Fixed an issue where title transient on PredictedPieceSet caused exception

fix: PredictedPieceSet getTitle fix

---

NEWS.md

Added NEWS.md section reflected in 1.1.3 release

chore: Post release 1.1.3

---

service/grails-app/migrations/update-mod-serials-management-1-1.groovy

Fixed an issue in which attempting to add a column with a nullable constraint caused systems with existing data to error
MODSER-88

fix: Nullable column migration

---

NEWS.md
service/gradle.properties
service/grails-app/migrations/update-mod-serials-management-1-1.groovy

Release 1.1.4

---

NEWS.md

Added NEWS.md section reflected in 1.1.5 release

chore: Post release 1.1.5

---

service/grails-app/domain/org/olf/templateConfig/templateMetadataRuleFormat/EnumerationTextualLevelTMRF.groovy
service/grails-app/views/templateMetadataRuleFormat/_enumerationTextualTMRF.gson

Added null checks for refdatacategory view and fixed the label being fetch with textual level class
UISER-191

fix: Textual enumeration level label

---

openapi/serials-management.yaml

Update API documentation for v2.0.0:
* Add modelrulesets
* Update enumeration and chronology label model
* Update textual enumeration model
* Bump version

MODSER-97: Update Serials API documentation

---

NEWS.md
service/gradle.properties

Added NEWS.md, updated version to 2.1.0-SNAPSHOT and okapiInterfaceVersion to 2.1

chore: Post release 2.0.0

---

service/grails-app/services/org/olf/PieceGenerationService.groovy

Fixed an issue in which creating a piece set with a combined last piece caused an error, implemented a condiitional for handling combination pieces
MODSER-103

MODSER-103: Error when attempting to create a piece set with a combined last piece

---

service/build.gradle

build: Update grails-okapi plugin to 7.4.0 to fix stability issues

---

NEWS.md

Added NEWS.md section reflected in 2.0.1 release

chore: Post release 2.0.1

---

NEWS.md

Added NEWS.md section reflecting 2.0.2 changes

docs: Post release 2.0.2

---

service/grails-app/migrations/update-mod-serials-management-1-2.groovy

Added primary key to enumeration/chronology template metadata rule table
MODSER-118

fix: Chronology//Enumeration template metadata rule primary key
